//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.25 at 02:53:21 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/examples/webservices/accountservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.examples.webservices.accountservice;
